### ISSUE TITLE
ComfyUI extension for LCM

### ISSUE THREAD

**Issue by jags111** [0xbitches/sd-webui-lcm#1]
Hey would love to make this work with comfyUI and is it possible to create a py script with installs for running this model inside including the VAE specific for this purpose inside comfyUI. Thanks for your work and understanding.

**Comment by 0xbitches** [comment]
I would consider attempting this if enough people request it. Unfortunately I do not have the luxury of time lately so I may have to reprioritize.

**Comment by AugmentedRealityCat** [comment]
Making LCM work with the rest of the Automatic1111 WebUI toolbox is much more important than porting it to other apps.
Don't let this distract you - there are comfy coders that can take care of this, some of them are even paid to do things like this by Stability AI.

**Comment by 0xbitches** [comment]
Here's a quick implementation for Comfy users: https://github.com/0xbitches/ComfyUI-LCM
