### ISSUE TITLE
Img2Img / Vid2Vid

### ISSUE THREAD

**Issue by 0xbitches** [0xbitches/sd-webui-lcm#16]
For ComfyUI users, img2img/vid2vid is already implemented: https://github.com/0xbitches/ComfyUI-LCM#img2img--vid2vid

Porting this to A1111 shouldn't be too hard.

**Comment by Amin456789** [comment]
nice!

**Comment by Amin456789** [comment]
there is an inpaint and outpaint for comfyui already, maybe u can get help porting it here?
https://github.com/taabata/lcm_inpaint-outpaint_comfy

**Comment by 0xbitches** [comment]
Completed in https://github.com/0xbitches/sd-webui-lcm/commit/70e4c30b2aa2cc95c0b9b9ab70f5aee55c53fb2a
