### ISSUE TITLE
sd-webui-lcm does not take the GPU device setting according to the platform

### ISSUE THREAD

**Issue by edwios** [0xbitches/sd-webui-lcm#22]
Instead of hardcoded to use "cuda", it should either take it from A1111 or use `torch.*.is_available()` to determine the GPU to be used on the platform it is executing.

**Comment by ljleb** [comment]
`modules.devices` exposes the inference device, we should use that IMO.

**Comment by 0xbitches** [comment]
Should be fixed in https://github.com/0xbitches/sd-webui-lcm/commit/bddc54285be81b0c45320d6ba9edc8d93fe39806.
