### ISSUE TITLE
producing only black images

### ISSUE THREAD

**Issue by YabbaYabbaYabba** [0xbitches/sd-webui-lcm#7]
Installed but every image is just a black square

**Comment by 0xbitches** [comment]
Does the console output an error message? There is too little information for me to help.

**Comment by YabbaYabbaYabba** [comment]
> Does the console output an error message? There is too little information for me to help.

Ooops.. silly me. Sorry about that , I did copy paste but it did not save.

I;m running on Manjaro Linux, GPU is AMD 6700XT (12Bg) RAM: 64Gb

command line starting with  : ./webui.sh --disable-nan-check

################################################################
Install script for stable-diffusion + Web UI
Tested on Debian 11 (Bullseye)
################################################################

################################################################
Running on mladenp user
################################################################

################################################################
Repo already cloned, using it as install directory
################################################################

################################################################
Create and activate python venv
################################################################

################################################################
Launching launch.py...
################################################################
Using TCMalloc: libtcmalloc_minimal.so.4
Python 3.11.5 (main, Sep  2 2023, 14:16:33) [GCC 13.2.1 20230801]
Version: v1.6.0
Commit hash: 5ef669de080814067961f28357256e8fe27544f4
Installing requirements
Installing sd-webui-controlnet requirement: changing opencv-python version from 4.7.0.72 to 4.8.0
Checking roop requirements
Install insightface==0.7.3
Installing sd-webui-roop requirement: insightface==0.7.3
Install onnx==1.14.0
Installing sd-webui-roop requirement: onnx==1.14.0
Install onnxruntime==1.15.0
Installing sd-webui-roop requirement: onnxruntime==1.15.0
Install opencv-python==4.7.0.72
Installing sd-webui-roop requirement: opencv-python==4.7.0.72
Launching Web UI with arguments: --disable-nan-check --upcast-sampling --opt-sub-quad-attention --no-half-vae
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
Civitai Helper: Get Custom Model Folder
Civitai Helper: Load setting from: /home/dr/sdxl/stable-diffusion-webui/stable-diffusion-webui/extensions/Stable-Diffusion-Webui-Civitai-Helper/setting.json
Civitai Helper: No setting file, use default
[-] ADetailer initialized. version: 23.10.1, num models: 9
2023-10-23 10:53:11,657 - ControlNet - INFO - ControlNet v1.1.411
ControlNet preprocessor location: /home/dr/sdxl/stable-diffusion-webui/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/downloads
2023-10-23 10:53:11,705 - ControlNet - INFO - ControlNet v1.1.411
Loading pipeline components...:  17%|██████████████▌                                                                        | 1/6 [00:00<00:01,  4.76it/s]
*** Error loading script: main.py
    Traceback (most recent call last):
      File "/home/dr/sdxl/stable-diffusion-webui/stable-diffusion-webui/modules/scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/dr/sdxl/stable-diffusion-webui/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 940, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/home/dr/sdxl/stable-diffusion-webui/stable-diffusion-webui/extensions/sd-webui-lcm/scripts/main.py", line 71, in <module>
        pipe = LatentConsistencyModelPipeline.from_pretrained(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/dr/sdxl/stable-diffusion-webui/stable-diffusion-webui/venv/lib/python3.11/site-packages/diffusers/pipelines/pipeline_utils.py", line 1105, in from_pretrained
        loaded_sub_model = load_sub_model(
                           ^^^^^^^^^^^^^^^
      File "/home/dr/sdxl/stable-diffusion-webui/stable-diffusion-webui/venv/lib/python3.11/site-packages/diffusers/pipelines/pipeline_utils.py", line 472, in load_sub_model
        loaded_sub_model = load_method(os.path.join(cached_folder, name), **loading_kwargs)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/dr/sdxl/stable-diffusion-webui/stable-diffusion-webui/venv/lib/python3.11/site-packages/transformers/tokenization_utils_base.py", line 1825, in from_pretrained
        return cls._from_pretrained(
               ^^^^^^^^^^^^^^^^^^^^^
      File "/home/dr/sdxl/stable-diffusion-webui/stable-diffusion-webui/venv/lib/python3.11/site-packages/transformers/tokenization_utils_base.py", line 2044, in _from_pretrained
        raise ValueError(
    ValueError: Non-consecutive added token '<|startoftext|>' found. Should have index 49408 but has index 49406 in saved vocabulary.

---
2023-10-23 10:53:12,400 - roop - INFO - roop v0.0.2-uncensored
2023-10-23 10:53:12,401 - roop - INFO - roop v0.0.2-uncensored
Loading weights [84feab3a32] from /home/dr/sdxl/stable-diffusion-webui/stable-diffusion-webui/models/Stable-diffusion/LCM_Dreamshaper_v7_4k.safetensors
Running on local URL:  http://127.0.0.1:7860
Creating model from config: /home/dr/sdxl/stable-diffusion-webui/stable-diffusion-webui/configs/v1-inference.yaml

To create a public link, set `share=True` in `launch()`.
Startup time: 30.6s (prepare environment: 24.5s, import torch: 2.3s, import gradio: 0.4s, setup paths: 0.4s, other imports: 0.4s, load scripts: 1.8s, create ui: 0.5s, gradio launch: 0.2s).
Applying attention optimization: sub-quadratic... done.
Model loaded in 2.2s (load weights from disk: 0.5s, create model: 1.1s, apply half(): 0.2s, calculate empty prompt: 0.2s).


There when running model :
Model loaded in 2.2s (load weights from disk: 0.5s, create model: 1.1s, apply half(): 0.2s, calculate empty prompt: 0.2s).
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 30/30 [00:06<00:00,  4.62it/s]
/home/mladenp/sdxl/stable-diffusion-webui/stable-diffusion-webui/modules/processing.py:906: RuntimeWarning: invalid value encountered in cast0,  4.66it/s]
  x_sample = x_sample.astype(np.uint8)
Total progress: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████| 30/30 [00:06<00:00,  4.55it/s]
Total progress: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████| 30/30 [00:06<00:00,  4.66it/s]

**Comment by 0xbitches** [comment]
Looks like LCM did not load properly due to a known issue: `ValueError: Non-consecutive added token '<|startoftext|>' found. Should have index 49408 but has index 49406 in saved vocabulary.` Please refer to https://github.com/0xbitches/sd-webui-lcm#known-issues for a detailed solution.

**Comment by YabbaYabbaYabba** [comment]
Sorry i know you closed this as resolved.

 I just cant find provided solution path or files. Search found nothing. Closest I've found is /home/user/sdxl/stable-diffusion-webui/stable-diffusion-webui/venv/lib/python3.11/site-packages/huggingface_hub/ but no added_tokens.json. file 

Does anyone have any idea where this should be on Linux?

**Comment by 0xbitches** [comment]
It should be under `~/.cache/` on linux. The path you provided is the path to the huggingface hub package itself, not the path to the model caches. 

Try running `ls ~/.cache/` or `echo $HF_HOME`

**Comment by YabbaYabbaYabba** [comment]
Thank you, will check that . Very excited to get this working :)

**Comment by YabbaYabbaYabba** [comment]
found it in :  ~/.cache/huggingface/hub/models--SimianLuo--LCM_Dreamshaper_v7/snapshots/c7f9b672c65a664af57d1de926819fd79cb26eb8/tokenizer/added_tokens.json

Thank you for your help, really appreciated !

Very fast!!!!

Applying attention optimization: sub-quadratic... done.
Model loaded in 2.0s (load weights from disk: 0.6s, create model: 1.0s, apply half(): 0.1s, calculate empty prompt: 0.2s).
LCM inference time:  0.5817761421203613 seconds
LCM inference time:  0.8696818351745605 seconds
LCM inference time:  0.8814699649810791 seconds
LCM inference time:  0.8761799335479736 seconds
LCM inference time:  0.8719279766082764 seconds
LCM inference time:  2.6093060970306396 seconds
LCM inference time:  2.518545150756836 seconds
LCM inference time:  2.5358474254608154 seconds
LCM inference time:  2.543264150619507 seconds

**Comment by sumeetprashant** [comment]
![lcm_a1111](https://github.com/0xbitches/sd-webui-lcm/assets/7965888/cae8d0e3-bddc-4594-8528-558e1df48a89)


I had a similar issue first images were black, now they are just noise and for some reason my folder here 

C:\Users\User Name\.cache\huggingface\hub\models--SimianLuo--LCM_Dreamshaper_v7\snapshots
\c255dc8f16c927b2a6af52092a5ec17903b3a24a\tokenizer

doesn't have the added_token.json file 
![no_added_tokens](https://github.com/0xbitches/sd-webui-lcm/assets/7965888/967c048b-942f-4a73-aac3-04f588ea44f0)

I have checked with VAE and without VAE, this issue persists.
