### ISSUE TITLE
some questions

### ISSUE THREAD

**Issue by Amin456789** [0xbitches/sd-webui-lcm#9]
HI!
first of all thank u

i see u r supporting fp16 too, my question is will u convert the main model to fp16 too? for lower size

does it support cpu ?

and could u please make it compatible with animatediff somehow? maybe by integrating the extension to the core of webui it will be possible

kind regards

**Comment by Amin456789** [comment]
@johnclaw check it out buddy, maybe it will be easier for u to install now

**Comment by 0xbitches** [comment]
@Amin456789 By lower size do you mean smaller disk space? This might be something the authors would be interested. For now I do not have the plan to do a fp16 model conversion. 
Cpu integration is planned: https://github.com/0xbitches/sd-webui-lcm/issues/5

**Comment by Amin456789** [comment]
yes i mean lower size for better cpu and ram usage, it has a safetensor in their huggingface page, maybe we can f16 it in webui model converter extension

anyway,  the fastsdcpu is being updated and it supports offline mode too, can u take a look at it please?
